### ISSUE TITLE
ipv4地址解析报错

### ISSUE THREAD

**Issue by peaksnail** [ipipdotnet/datx-nodejs#3]
你好，使用官方事例代码，报错如下：
1 
> datx = require('ipip-datx')
{ City: [Function: City], District: [Function: District] }

2
> dis =new  datx.District('./17monipdb.datx')
District {
  data: <Buffer 00 29 62 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... >,
  indexSize: 2712066 }

3
> dis.findSync('123.121.17.72')
    RangeError: out of range index
    at Buffer.copy (buffer.js:598:18)
    at District.findSync (/project/test/node_modules/ipip-datx/lib/district.js:64:27)
    at repl:1:5
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:440:10)
    at emitOne (events.js:120:20)
    at REPLServer.emit (events.js:210:7)

ipip-datx版本 ipip-datx@0.2.2
谢谢

**Comment by ipipdotnet** [comment]
你应该使用datx.City

**Comment by peaksnail** [comment]
datx.City 一样的错误
